"""empty message
Revision ID: 313f4c5508bd
Revises: 455fedde7704
Create Date: 2022-05-07 19:53:23.515261
"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "313f4c5508bd"
down_revision = "455fedde7704"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_variant", sa.Column("badge", sa.String(length=10), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_variant", "badge")
    # ### end Alembic commands ###