"""empty message
Revision ID: 455fedde7704
Revises: c97d6515e6d3
Create Date: 2022-05-05 13:00:33.354916
"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '455fedde7704'
down_revision = 'c97d6515e6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_variant',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('game_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('preview_file_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['preview_file_id'], ['preview_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_variant_game_id'), 'game_variant', ['game_id'], unique=False)
    op.create_table('variant_link',
    sa.Column('person_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('variant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['game_variant.id'], )
    )
    op.alter_column('game_score', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.execute("UPDATE person SET coins = 0")
    op.alter_column('person', 'coins',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'coins',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_score', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('variant_link')
    op.drop_index(op.f('ix_game_variant_game_id'), table_name='game_variant')
    op.drop_table('game_variant')
    # ### end Alembic commands ###