"""empty message
Revision ID: ac703f2b9f45
Revises: 6546b82d6e24
Create Date: 2022-04-14 10:31:51.374413
"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ac703f2b9f45'
down_revision = '6546b82d6e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('render_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'render_time')
    # ### end Alembic commands ###