"""empty message
Revision ID: ed23d9f7115c
Revises: ac703f2b9f45
Create Date: 2022-04-21 16:08:13.026015
"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ed23d9f7115c'
down_revision = 'ac703f2b9f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'color')
    # ### end Alembic commands ###